In [1]:
cd ~/packages/WaveFunctionCollapse

/Users/feldman/packages/WaveFunctionCollapse


In [2]:
import wfc
from wfc import *
%load_ext autoreload
%autoreload 2

In [3]:
from lasagna.imports import *
import lasagna.io
j = lasagna.config.j = start_client()
dr = ((0, 1),)*100
def show(*args, **kwargs):
    lasagna.io.show_IJ(*args, display_ranges=dr, **kwargs)

In [26]:
N = 3
FMX = N*9
FMY = N*4

a = (1, 0, 1)
b = (0, 1, 0)
c = (1, 1, 1)
d = (0, 0, 0)

T = rotate((c,b,b), 4)
X = rotate((a,b,a), 1)
I = rotate((c,b,c), 2)


initial = [(a,b,a), (b,a,b), (b,b,b), (a,a,a)]
initial = T

filename = 'samples/Platformer.png'
initial = initial_from_png(filename, N);

model = SimpleTiledModel(N,FMX,FMY,initial)
arr = []

In [27]:
model.wave = np.random.choice([True, False], p=[0.9,0.1], size=model.wave.shape)
# model.wave[0,:,:] = True

In [30]:
%timeit -n1 -r1 model.propagate_from(zip_where(model.wave.sum(axis=0)))

propagation modified 0 points
1 loop, best of 1: 688 ms per loop


In [29]:
%prun model.propagate_from(zip_where(model.wave.sum(axis=0)))

propagation modified 0 points
 

In [21]:
np.where(model.wave[:,3,4])

(array([ 6, 54, 56, 60, 66, 67, 70, 81, 83, 97]),)

In [7]:
model.wave.sum(axis=0)

array([[51, 47, 43, 50, 39, 37, 39, 35, 41, 39, 31, 35, 39, 35, 39, 38, 37,
        39, 38, 41, 35, 30, 26, 29, 35, 45, 48],
       [38, 35, 33, 33, 33, 30, 37, 34, 39, 32, 29, 36, 39, 30, 33, 30, 29,
        27, 30, 33, 31, 35, 29, 28, 40, 46, 47],
       [21, 19, 20, 23, 28, 32, 35, 30, 34, 31, 30, 40, 37, 29, 32, 24, 22,
        17, 23, 23, 26, 35, 27, 28, 40, 46, 46],
       [18, 14, 14, 17, 17, 20, 25, 18, 21, 26, 27, 32, 24, 21, 17, 13, 11,
        10, 15, 13, 17, 26, 25, 30, 41, 48, 44],
       [18, 17, 18, 18, 15, 11, 16, 16, 17, 19, 16, 19, 16, 14, 10,  9,  6,
         6, 10,  9, 14, 18, 20, 24, 34, 36, 40],
       [19, 15, 16, 15, 14, 10, 12, 12, 12, 14, 12, 13, 12,  9,  8,  8,  7,
         5,  8, 10, 13, 12, 13, 13, 22, 25, 34],
       [17, 14, 16, 14, 11,  8, 11, 13, 12, 11,  8,  9,  8,  6,  7,  7,  7,
         4,  6,  9, 12, 13, 15, 14, 18, 19, 26],
       [19, 16, 18, 18, 16, 10, 12, 15, 13, 15, 13,  9,  8,  7,  9, 10,  8,
         6,  7,  8,  9, 14, 16, 13, 17, 17, 23],


In [383]:
for i in range(200):
    done = model.update()
    if done:
        break
    arr += [model.get_superposition()]
print i

collapsed (4, 25)
collapsed (3, 25)
collapsed (2, 25)
collapsed (1, 25)
collapsed (0, 25)
collapsed (2, 24)
collapsed (1, 22)
collapsed (3, 24)
collapsed (2, 20)
collapsed (5, 24)
collapsed (4, 15)
collapsed (4, 13)
collapsed (2, 16)
collapsed (5, 25)
collapsed (1, 15)
collapsed (4, 16)
collapsed (9, 11)
collapsed (4, 12)
collapsed (6, 19)
collapsed (2, 6)
collapsed (3, 1)
collapsed (11, 11)
collapsed (8, 19)
collapsed (7, 21)
collapsed (9, 17)
collapsed (1, 8)
collapsed (0, 7)
collapsed (11, 0)
collapsed (2, 1)
collapsed (4, 2)
collapsed (9, 19)
collapsed (0, 15)
collapsed (11, 24)
collapsed (3, 2)
collapsed (9, 25)
collapsed (0, 17)
collapsed (0, 24)
collapsed (0, 22)
collapsed (0, 18)
collapsed (8, 26)
collapsed (6, 26)
collapsed (4, 26)
collapsed (1, 1)
collapsed (0, 1)
collapsed (1, 26)
collapsed (0, 5)
collapsed (0, 3)
collapsed (0, 26)
all points collapsed
48


In [384]:
model.wave.sum(axis=0)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1],
       [1, 1, 1, 1, 

In [388]:
arr = np.array(arr)
skimage.external.tifffile.imsave('Platformer_run.tif', arr.astype(np.float32))

In [386]:
show(model.get_superposition(), 'superposition')
# show(model.get_entropy(), 'entropy')
# show(model.wave.sum(axis=0), 'wavesum')
# show(model.initial, 'initial')

Cast float64 to float32
